name:                system-info
version:             0.5.0.0
github:              "ChaosGroup/system-info"
license:             MIT
author:              "Daniel Taskoff"
maintainer:          "daniel.taskoff@gmail.com"
copyright:           "2020 (c) ChaosGroup"

synopsis:            Get the name of the operating system
category:            System

description:         Please see the README on Github at <https://github.com/ChaosGroup/system-info#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

  when:
  - condition: os(windows)
    then:
      dependencies:
      - Win32
      extra-libraries: ole32, oleaut32, wbemuuid
      c-sources: csrc/wmi.c
    else:
      c-sources: csrc/uname.c

ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates
